### ISSUE TITLE
Package has nested tools directories. 

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [itigoag/chocolatey.adobe-acrobat-reader-dc#16]
This package has nested tools directories, so the `chocolateyinstall.ps1` and `chocolateyuninstall.ps1` scripts are in `\tools\tools\` rather then in `\tools\`. 

![image](https://user-images.githubusercontent.com/38865330/77982404-e42b5d80-72d1-11ea-90b5-fbc92a3db213.png)

It would be good if they were moved to the standard `\tools\` directory.

**Comment by sbaerlocher** [comment]
Thanks for your feedback, I see that it is only since the last 3 versions. I'll have a look at what the trigger is because a conscious move to a sub under folder did not happen.

**Comment by TheCakeIsNaOH** [comment]
Seems to be fixed in the latest version, thanks @sbaerlocher.
