### ISSUE TITLE
(adobereader) ENHANCEMENT: Add package parameter to disable ARM service

### ISSUE THREAD

**Issue by bcurran3** [itigoag/chocolatey.adobe-acrobat-reader-dc#5]
REF: https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotes/10/10.1.4.html

>  Like Reader 10.1 and later, Acrobat 10.1.4 installs ARMsvc.exe as part of the Updater on Windows 7, Vista, and Server 2008, Acrobat 10.1.4. The new service enables silent and automatic updates on machines where a user has configured the application for automatic updates. The service eliminates information dialogs prior to updates. In enterprise settings, IT can use DISABLE_ARM_SERVICE_INSTALL=1 to prevent the installation of the ARM service.

Chocolatey should be, or the a choice to be, the preferred update method. :)

PRIORITY: LOW
This will suffice: 
https://chocolatey.org/packages/adobereader-disable-updates-winconfig/0.0.1

**Comment by sbaerlocher** [comment]
Thanks for the issue, this is a good idea I will implement this.
